#!/usr/bin/with-contenv bash

echo "[LogViewer] waiting for RClone service to be ready before running sa-rotate"
s6-svwait ../media-rclone && sleep 60

umask 022

exec \
        s6-setuidgid abc bash rotate.sh
