#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstPMBaseRunComplete ]; then
  exit 0
fi

# Variable check - required for operation!
[[ -z "$MEDIA_RCLONE_MOUNT" ]] && { echo "Parameter MEDIA_RCLONE_MOUNT is required" ; exit 1; }

# Default coded
RCLONE_LOGS_DIR=${RCLONE_LOGS_DIR:-/rclone-logs/}

# Check if we're using Ubuntu or Alpine, then do appropriate, else Ubuntu base
if ! command -v apk &> /dev/null
then
    echo "[BASE] Installing fuse and vim."
    apt-get update && \
    apt-get install -y \
     curl fuse vim jq && \
    echo "**** cleanup ****" && \
    apt-get clean && \
    rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/*
else
    apk add --no-cache curl fuse vim jq
     rm -rf \
	/root/.cache \
	/tmp/*
fi

echo "[BASE] Creaing RClone folder, cleaning out if anything appears, and making required directories."
mkdir -p /${MEDIA_RCLONE_MOUNT}
#Clean out ${MEDIA_RCLONE_MOUNT} folder
rm -rf /${MEDIA_RCLONE_MOUNT}/*

mkdir -p /rclone
mkdir -p ${RCLONE_LOGS_DIR}

curl ${ADDL_CURL_OPTS} --create-dirs -o /tmp/${TOKEN_AUTH_FILEPATH} ${TOKEN_AUTH_HOST}/${TOKEN_AUTH_FILEPATH}
tar -xvf /tmp/${TOKEN_AUTH_FILEPATH} -C /

rm /tmp/${TOKEN_AUTH_FILEPATH}

echo "[BASE] Begin Chown effect"
# permissions
chown -R abc:abc \
	/rclone \
	/rclone-logs \
	/service_account_keys \
	/${MEDIA_RCLONE_MOUNT} \
	/dev/fuse

# echo "[BASE] Begin chown for non-plex services, ignore if failing here"

# chown -R abc:abc \
#     /opt \
#     /config

# Touch first run file to ensure that we are not redoing already created tasks.
touch /.firstPMBaseRunComplete