#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstLogViwerPMBase ]; then
  exit 0
fi

if [ ${ENABLE_LOGVIEWER} == "true" ]; then

  # mkdir -p /serve-logs/

  # curl ${ADDL_CURL_OPTS} --create-dirs -o /tmp/${SERVE_LOGS_FILEPATH} ${TOKEN_AUTH_HOST}/exes/${SERVE_LOGS_FILEPATH}
  # tar -xvf /tmp/${SERVE_LOGS_FILEPATH} -C /serve-logs/

  # rm /tmp/${SERVE_LOGS_FILEPATH}

  # Touch first run file to ensure that we are not redoing already created tasks.
  touch /.firstLogViwerPMBase
fi