#!/usr/bin/with-contenv bash

if [ ${ENABLE_AUTOSCAN} == "true" ]; then
    echo "[Autoscan] waiting for Plex service to be ready"
    s6-svwait ../plex && sleep 15

    echo "[Autoscan] autoscan starting..."
    exec s6-setuidgid abc /autoscan/autoscan --config=/autoscan/autoscan_config.yml --database=/autoscan/autoscan.db --log=/autoscan/autoscan.log -v
else
    while :
    do
        echo "Running script to keep service alive; Legacy PAS is not running"
        sleep 86400
    done
fi
