#!/usr/bin/with-contenv bash


if [ ${ENABLE_LOGVIEWER} == "true" ]; then
    echo "[LogViewer] waiting for RClone service to be ready"
    s6-svwait ../media-rclone && sleep 60

    echo "[LogViewer] LogViewer starting..."
	umask 022

	exec \
		s6-setuidgid abc /serve-logs/serve/serve --host 0.0.0.0 --port ${SERVE_LOGS_PORT:-8765} ${LOGS_PREFIX_TO_TAIL:---prefix /rclone-logs}
else
    while :
    do
        echo "Running script to keep service alive; [LogViewer] is not running"
        sleep 86400
    done
fi
