#!/usr/bin/with-contenv bash

# Setup Cloudflared tunnel

umask 022

if [ ${ENABLE_CLOUDFLARED} == "true" ]; then
    exec \
        /usr/local/bin/cloudflared ${CLOUDFLARED_TUNNEL_OPTS} tunnel ${CLOUDFLARED_TUNNEL_COMMAND_OPTS} --config ${CLOUDFLARED_CONFIG} run ${TUNNEL_NAME_OR_UUID}
else
    while :
    do
        echo "Running script to keep service alive; Cloudflared is not running"
        sleep 86400
    done
fi