#!/usr/bin/with-contenv bash

[[ -z "$RCLONE_CONFIG_NAME" ]] && { echo "Parameter RCLONE_CONFIG_NAME is required" ; exit 1; }

echo "[SARotate] Chown'ing SA Rotate files"
chown -R abc:abc /etc/s6-overlay/s6-rc.d/sa-rotate
chmod +x /etc/s6-overlay/s6-rc.d/sa-rotate/run
chmod +x /etc/s6-overlay/s6-rc.d/sa-rotate/rotate.sh

touch /etc/s6-overlay/s6-rc.d/user/contents.d/media-rclone
