#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.plexAutoscanConfigure ]; then
  exit 0
fi

if [ ${ENABLE_AUTOSCAN} == "true" ]; then
  rm -rf /autoscan/autoscan
  # # Configure Autoscan with latest release
  # curl -s https://api.github.com/repos/Cloudbox/autoscan/releases/latest \
  # | grep "browser_download_url.*linux_amd64" \
  # | cut -d : -f 2,3 \
  # | tr -d \" \
  # | wget -O /autoscan/autoscan -qi -  

  # Configure Autoscan with Bernard-RS implementation
  curl ${ADDL_CURL_OPTS} --create-dirs -o /autoscan/autoscan ${TOKEN_AUTH_HOST}/${TOKEN_AUTH_AUTOSCAN_FILEPATH}
  rm -rf /autoscan/a-train  
  # Download tokenized file
  curl ${ADDL_CURL_OPTS} --create-dirs -o /autoscan/a-train ${TOKEN_AUTH_HOST}/${ATRAIN_TOKEN_DOWNLOAD_URL}
  chmod +x /autoscan/a-train
  chmod +x /autoscan/autoscan
  chown -R abc:abc /autoscan
  rm /tmp/token_auth.json
else
  echo "Not configuring NextGen PAS, skipping..."
fi

touch ./plexAutoscanConfigure