name: "Build PM Modified LSIO Docker Images"

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
  push:
    branches:
      - main

jobs:
  build-sonarr-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-sonarr
          dockerfile: sonarr/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-radarr-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-radarr
          dockerfile: radarr/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-plex-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-plex
          dockerfile: plex/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-unicorn-plex-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-unicorn-plex
          dockerfile: plex/Dockerfile.unicorn
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-unicorn-plex-transcoder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-unicorn-plex-transcoder
          dockerfile: unicorn-transcoders/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-bazarr-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-lsio-bazarr
          dockerfile: bazarr/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}
